# Generated by Django 2.0.4 on 2018-04-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pip',
            name='title',
            field=models.CharField(max_length=90, unique=True),
        ),
    ]
