# Generated by Django 2.0.4 on 2018-05-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180429_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='pip',
            name='pipId',
            field=models.CharField(default='P2018001', max_length=8, unique=True, verbose_name='Id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pip',
            name='client',
            field=models.CharField(max_length=30, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pip',
            name='cost_estimates',
            field=models.CharField(max_length=60, verbose_name='Estimativa de Gastos'),
        ),
        migrations.AlterField(
            model_name='pip',
            name='justification',
            field=models.TextField(verbose_name='Justificativa'),
        ),
        migrations.AlterField(
            model_name='pip',
            name='objectives',
            field=models.TextField(verbose_name='Objetivos'),
        ),
        migrations.AlterField(
            model_name='pip',
            name='orgUnit',
            field=models.CharField(max_length=10, verbose_name='Unidade Solicitante'),
        ),
        migrations.AlterField(
            model_name='pip',
            name='title',
            field=models.CharField(max_length=90, unique=True, verbose_name='Título'),
        ),
    ]
